import { League_Spartan, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-league-spartan",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.variable} ${montserrat.variable}`}>
        <Header />
        {children}
       

        
        </body>
    </html>
  );
}
